### PR TITLE
Fix Tooltip Display

### PR DESCRIPTION
**Pull request by sprankhub**

### CODE REVIEW

**Comment by sprankhub** [comment]
Please do not merge yet.

**Comment by sprankhub** [comment]
This is now ready to be merged, @Spaggel. I am really sorry, but I actually broke the whole tooltip display with my multistore support stuff. Anyway, I fixed this now and also improved a lot of stuff. Could you merge the two pull requests and release a new version? Thanks!

**Comment by sprankhub** [comment]
Could you please merge this and the other PR, @Spaggel? :-)

**Comment by Spaggel** [comment]
Yes! I'll look into it asap!

**Pull request merged**
